parameters:
    'app.ENABLE_CORS': true # Enable CORS for API using
    'app.ENABLE_LOCALE': true # Enable CORS for API using


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'



    # ---------------------------------------------------------------------------
    # Controllers
    # ---------------------------------------------------------------------------
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Web controllers
    # ---------------------------------------------------------------------------
    App\Controller\Web\:
        resource: '../src/Controller/Web'
        tags: ['controller.service_arguments']

    # Api controllers
    # ---------------------------------------------------------------------------
    App\Controller\Api\:
        resource: '../src/Controller/Api'
        tags: ['controller.service_arguments']



    # ---------------------------------------------------------------------------
    # Security services
    # ---------------------------------------------------------------------------
    App\Security\:
        resource: '../src/Security'



    # ---------------------------------------------------------------------------
    # Services
    # ---------------------------------------------------------------------------
    App\Service\:
        resource: '../src/Service'

    # Middleware service that perform after-controller operations for api queries
    # ---------------------------------------------------------------------------
    App\Service\Api\EnableApi\:
        resource: '../src/Service/Api/EnableApi'
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: 254 }
        bind:
            $enableCORS: '%app.ENABLE_CORS%' #Check ENABLE_CORS variable from this config

    # Middleware service that determine & setup user locale
    # ---------------------------------------------------------------------------
    App\Service\Locale\:
        resource: '../src/Service/Locale'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20 }
        bind:
            $enableLocale: '%app.ENABLE_LOCALE%' # Check ENABLE_CORS variable from this config
            $defaultLocale: '%kernel.default_locale%' # Default locale from translation.yaml

    # Store user locale in session based on user entity
    # ---------------------------------------------------------------------------
    App\Service\Locale\EventSubscriber\:
        resource: '../src/Service/Locale/EventSubscriber'
        bind:
             $enableLocale: '%app.ENABLE_LOCALE%' # Check ENABLE_CORS variable from this config
             $defaultLocale: '%kernel.default_locale%' # Default locale from translation.yaml